### ISSUE TITLE
Enhancement: Default todo list item creation

### ISSUE THREAD

**Issue by axonxorz** [MuntasirSauvik/WebDevelopmentBootcamp#5]
Currently, if you remove all todos from the list, the application server will automatically re-create the default todos. It should only create the default todos on server startup, and only if no other todos exist

**Comment by MuntasirSauvik** [comment]
but when all todos are removed is it not the case that no other todos exist, thus repopulate with default??

**Comment by MuntasirSauvik** [comment]
Resolved this issue, now todolist only populates on start of app.
