### ISSUE TITLE
Enhancement: Mark as complete without deleting

### ISSUE THREAD

**Issue by axonxorz** [MuntasirSauvik/WebDevelopmentBootcamp#6]
If I mark a todo as complete, it should be crossed out and marked as completed, without deleting it.

The use case is if I accidentally mark an item complete, it's immediately lost permanently.

You could have another button at the bottom "Remove completed todos" that would trigger the deletion

**Comment by MuntasirSauvik** [comment]
Mark as complete implemented, now new button exists which is used to clear the marked complete items.
